namespace Sperlich.Easing {
	public enum EaseType {
		InQuad = 0,
		OutQuad = 1,
		InOutQuad = 2,
		InCubic = 3,
		OutCubic = 4,
		InOutCubic = 5,
		InQuart = 6,
		OutQuart = 7,
		InOutQuart = 8,
		InQuint = 9,
		OutQuint = 10,
		InOutQuint = 11,
		InSine = 12,
		OutSine = 13,
		InOutSine = 14,
		InExpo = 15,
		OutExpo = 16,
		InOutExpo = 17,
		InCirc = 18,
		OutCirc = 19,
		InOutCirc = 20,
		Linear = 21,
		Spring = 22,
		InBounce = 23,
		OutBounce = 24,
		InOutBounce = 25,
		InBack = 26,
		OutBack = 27,
		InOutBack = 28,
		InElastic = 29,
		OutElastic = 30,
		InOutElastic = 31,
		Step = 32,
	}
}